name: Called workflow

on:
  workflow_call:
    inputs:
      flavor:
        description: 'ice cream flavor'
        required: false
        default: 'chocolate'
        type: string
      environment:
        description: 'test or prod'
        required: true
        type: string

env:
  good_taste: inputs.flavor == 'chocolate'

jobs:
  buildArtifact:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: is this good
        run: |
          echo "do we have good taste? ${{ env.good_taste }}"

      - name: store secret in file
        run: |
          echo "${{ secrets.MYVAR }}" > FILE
          cat FILE

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: ${{ inputs.flavor == 'vanilla' }}
