name: Build and deploy release

on:
  push:
    tags:
      - 'v*'

env:
  is_prerelease: ${{ contains(github.ref, 'pre') }}

jobs:
  test:
    if: contains(github.ref, 'pre')
    uses: ./.github/workflows/called.yml
    with:
      flavor: vanilla

  test2:
    if: ${{ !contains(github.ref, 'pre' )}}
    uses: ./.github/workflows/called.yml
    with:
      flavor: rockyroad

  testVariables:
    runs-on: ubuntu-latest

    steps:
      - name: echo pre-release. just here for debugging
        run: echo "ref ${{ github.ref }}. is prelease? $is_prerelease"

      - name: echo prerelease
        run: echo "prerelease ${{ github.ref }}. prerelease is $is_prerelease"
        if: env.is_prerelease == 'true'

      - name: echo release
        run: echo "release ${{ github.ref }}. prerelease is $is_prerelease"
        if: env.is_prerelease == 'false'
