name: Echo tag message

on:
  push:
    tags:
      - 'tm-*'

jobs:
  doTheThing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: get tag message
        run: echo "$(git show -s --pretty='' ${{ github.ref_name }})"
      # - name: echo webhook
      #   run: echo "commit message ${{ github.event.description }}. commits ${{ toJSON(github.event) }}"
